### ISSUE TITLE
Get maintained

### ISSUE THREAD

**Issue by wolneykien** [OpenSC/pam_pkcs11#27]
Hi Ludovic!

I currently maintain the package in Sisyphus and already have [a number of patches](http://sisyphus.ru/en/srpm/Sisyphus/pam_pkcs11/patches) I want to integrate. If you're really looking for a new maintainer, I can take it over.

**Comment by LudovicRousseau** [comment]
Sorry I don't think I noticed your proposal before.
Do you still volunteer to maintain pam_pkcs11?

**Comment by wolneykien** [comment]
Hi! Probably, yes.

I've made a special version for Sisyphus with many new configuration [options](http://git.altlinux.org/people/manowar/packages/?p=pam_pkcs11.git;a=blob;f=pam_pkcs11/src/pam_pkcs11/pam_config.h;h=2c17b03c855143c73d37097d2e2e31f0c0a360eb;hb=e70d52cd64e229480363055884691ee59ee6f690), configurable prompts, and low-level modules (a card-specific implementation to get an exact number of PIN attempts, for instance).

However, I don't think all of that is really needed in the mainstream pam_pkcs11 project. So, what are the criteria of updating / maintaining the mainstream version?

**Comment by LudovicRousseau** [comment]
I just sent you an invitation to join the "pam_pkcs11 maintainers" group.

It is now up to you to decide what you want to do with pam_pkcs11 :-)
You can even include card specific code. Maybe with the possibility to disable it or not enable it by default.

**Comment by frankmorgner** [comment]
@wolneykien please create a new release, because there were some security issues discovered (https://www.x41-dsec.de/lab/advisories/x41-2018-003-pam_pkcs11/). I've fixed all of them upstream, but I'll leave the testing, packaging and write up of some release notes to you. Maybe you also want to cherry-pick some of your more generic changes.

**Comment by wolneykien** [comment]
Hi, guys! Note the #48 issue!

**Comment by LudovicRousseau** [comment]
@frankmorgner I see nothing new in master since the 0.6.11 release I made in May 2019.
I guess the commits your are talking about are already present in release 0.6.11.
If that is not the case then please be more specific.

**Comment by LudovicRousseau** [comment]
@wolneykien I propose you to create Pull Requests with your changes rebased on the current master. Since you created different branches it should be easy to create different PR. Of course the order is important since some patches depend on other ones.

If nobody complains after some days you can merge/apply them yourself.
